"""Typed Markdown documents for Cortex human views.

The V12 ledger stores opaque JSON.  This module is the only layer that knows
how a presentation document becomes Markdown. The renderer owns the standard
document sections and typed blocks, while authored Markdown inside semantic
text is preserved byte-for-byte after newline normalization. Human views are
derived display artifacts and never become ledger authority.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import re
from collections.abc import Mapping, Sequence
from typing import Any, TypeAlias


def _normalise(value: object) -> str:
    """Return readable text with canonical newlines and no implicit ``None``."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return str(value).replace("\r\n", "\n").replace("\r", "\n")


def plain_text(value: object) -> str:
    """Expose normalized plain text for callers that need a safe inline value.

    This intentionally does not globally escape Markdown punctuation.  The
    renderer preserves authored Markdown in each block below.
    """
    return _normalise(value)


def _escape_inline_markup(text: str) -> str:
    """Preserve authored inline Markdown without renderer-added escaping."""
    return text


def _escape_structural_line(line: str) -> str:
    """Preserve authored block Markdown without renderer-added escaping."""
    return line


def safe_paragraph_text(value: object) -> str:
    """Normalize paragraph text while preserving authored Markdown."""
    return "\n".join(_escape_structural_line(_escape_inline_markup(line)) for line in _normalise(value).split("\n"))


def safe_inline_text(value: object) -> str:
    """Normalize one-line labels and values without escaping inline Markdown."""
    text = _normalise(value)
    # A line break inside a key/value, heading, or table cell must not start a
    # new Markdown block.  Spaces are readable and preserve all words.
    return _escape_inline_markup(" ".join(part.strip() for part in text.split("\n") if part.strip()))


def safe_heading_text(value: object, *, fallback: str = "Section") -> str:
    """Return one readable line suitable after a renderer-owned heading token."""
    text = safe_inline_text(value).strip()
    if not text:
        return fallback
    # The heading token is generated by this module. A newline is collapsed
    # above so a label remains one line without rewriting its Markdown.
    return text


def _is_sequence(value: object) -> bool:
    return isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray))


def _nonempty(value: object) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if _is_sequence(value) or isinstance(value, Mapping):
        return bool(value)
    return True


def _display_value(value: object) -> str:
    """Flatten a legacy value for one typed list item."""
    if isinstance(value, Mapping):
        values: list[str] = []
        for key, item in value.items():
            if not _nonempty(item):
                continue
            values.append(f"{safe_inline_text(key)}: {_display_value(item)}")
        return "; ".join(values) or "(empty)"
    if _is_sequence(value):
        return "; ".join(_display_value(item) for item in value if _nonempty(item)) or "(empty)"
    return safe_inline_text(value) or "(empty)"


@dataclass(frozen=True)
class Paragraph:
    text: object


@dataclass(frozen=True)
class KeyValue:
    label: object
    value: object


@dataclass(frozen=True)
class BulletList:
    items: tuple[object, ...] = field(default_factory=tuple)

    def __init__(self, items: Sequence[object] | None = None) -> None:
        object.__setattr__(self, "items", tuple(items or ()))


@dataclass(frozen=True)
class OrderedSteps:
    items: tuple[object, ...] = field(default_factory=tuple)

    def __init__(self, items: Sequence[object] | None = None) -> None:
        object.__setattr__(self, "items", tuple(items or ()))


@dataclass(frozen=True)
class Checklist:
    items: tuple[object, ...] = field(default_factory=tuple)

    def __init__(self, items: Sequence[object] | None = None) -> None:
        object.__setattr__(self, "items", tuple(items or ()))


@dataclass(frozen=True)
class Table:
    columns: tuple[object, ...] = field(default_factory=tuple)
    rows: tuple[tuple[object, ...], ...] = field(default_factory=tuple)

    def __init__(
        self,
        columns: Sequence[object] | None = None,
        rows: Sequence[Sequence[object]] | None = None,
    ) -> None:
        object.__setattr__(self, "columns", tuple(columns or ()))
        object.__setattr__(self, "rows", tuple(tuple(row) for row in (rows or ())))


@dataclass(frozen=True)
class CodeBlock:
    code: object
    language: object | None = None


@dataclass(frozen=True)
class Callout:
    text: object
    label: object | None = None


@dataclass(frozen=True)
class Finding:
    title: object
    severity: object | None = None
    location: object | None = None
    impact: object | None = None
    evidence: object | None = None
    recommendation: object | None = None
    coverage: object | None = None
    residual_risk: object | None = None
    conclusion: object | None = None
    details: object | None = None


Block: TypeAlias = (
    Paragraph
    | KeyValue
    | BulletList
    | OrderedSteps
    | Checklist
    | Table
    | CodeBlock
    | Callout
    | Finding
)


@dataclass(frozen=True)
class Section:
    title: object
    blocks: tuple[Block, ...] = field(default_factory=tuple)

    def __init__(self, title: object, blocks: Sequence[Block] | None = None) -> None:
        object.__setattr__(self, "title", title)
        object.__setattr__(self, "blocks", tuple(blocks or ()))

    def is_empty(self) -> bool:
        return not any(block_is_visible(block) for block in self.blocks)


@dataclass(frozen=True)
class Document:
    title: object
    status: object | None = None
    summary: object | None = None
    sections: tuple[Section, ...] = field(default_factory=tuple)
    metadata: tuple[KeyValue, ...] = field(default_factory=tuple)

    def __init__(
        self,
        title: object,
        status: object | None = None,
        summary: object | None = None,
        sections: Sequence[Section] | None = None,
        metadata: Sequence[KeyValue] | Mapping[object, object] | None = None,
    ) -> None:
        object.__setattr__(self, "title", title)
        object.__setattr__(self, "status", status)
        object.__setattr__(self, "summary", summary)
        object.__setattr__(self, "sections", tuple(sections or ()))
        if isinstance(metadata, Mapping):
            metadata_values = tuple(KeyValue(key, value) for key, value in metadata.items())
        else:
            metadata_values = tuple(metadata or ())
        object.__setattr__(self, "metadata", metadata_values)

    def render(self) -> str:
        return render_markdown(self)


MarkdownDocument = Document


def block_is_visible(block: object) -> bool:
    """Whether a typed block has content worth placing in a view."""
    if isinstance(block, Paragraph):
        return _nonempty(block.text)
    if isinstance(block, KeyValue):
        return _nonempty(block.label) and _nonempty(block.value)
    if isinstance(block, (BulletList, OrderedSteps, Checklist)):
        return any(_nonempty(item) for item in block.items)
    if isinstance(block, Table):
        return bool(block.columns) and bool(block.rows)
    if isinstance(block, CodeBlock):
        return _nonempty(block.code)
    if isinstance(block, Callout):
        return _nonempty(block.text)
    if isinstance(block, Finding):
        return _nonempty(block.title) or any(
            _nonempty(value)
            for value in (
                block.severity,
                block.location,
                block.impact,
                block.evidence,
                block.recommendation,
                block.coverage,
                block.residual_risk,
                block.conclusion,
            )
        ) or bool(block.details and any(_nonempty(value) for value in block.details.values()))
    return False


def _item_text(item: object) -> tuple[str, Sequence[object] | None]:
    """Extract a readable primary value and optional typed children."""
    if isinstance(item, Mapping):
        primary: object | None = None
        for key in ("text", "label", "value", "name", "title", "item"):
            if key in item and _nonempty(item[key]):
                primary = item[key]
                break
        children = next(
            (
                item[key]
                for key in ("items", "children", "steps", "subitems")
                if _is_sequence(item.get(key))
            ),
            None,
        )
        if primary is not None:
            return _display_value(primary), children
        return _display_value(item), children
    if _is_sequence(item):
        return _display_value(item), None
    return safe_inline_text(item) or "(empty)", None


def _render_list(block: BulletList | OrderedSteps | Checklist, *, ordered: bool = False) -> list[str]:
    visible = [item for item in block.items if _nonempty(item)]
    if not visible:
        return []
    lines: list[str] = []
    for index, item in enumerate(visible, start=1):
        text, children = _item_text(item)
        if isinstance(block, Checklist):
            checked = False
            if isinstance(item, Mapping):
                checked = bool(item.get("checked", item.get("complete", item.get("done", False))))
            elif isinstance(item, (tuple, list)) and len(item) == 2 and isinstance(item[0], bool):
                checked, text = item[0], safe_inline_text(item[1]) or "(empty)"
            marker = "[x]" if checked else "[ ]"
            prefix = f"- {marker}"
        elif ordered:
            prefix = f"{index}."
        else:
            prefix = "-"
        lines.append(f"{prefix} {text}".rstrip())
        if children:
            nested = _render_nested_items(children)
            lines.extend("    " + line for line in nested)
    return lines


def _render_nested_items(items: Sequence[object]) -> list[str]:
    lines: list[str] = []
    for item in items:
        text, children = _item_text(item)
        lines.append(f"- {text}".rstrip())
        if children:
            lines.extend("    " + line for line in _render_nested_items(children))
    return lines


def _table_cell(value: object) -> str:
    text = safe_inline_text(value)
    return text or " "


def _fence(code: str) -> str:
    longest_tick = max((len(run) for run in re.findall(r"`+", code)), default=0)
    longest_tilde = max((len(run) for run in re.findall(r"~+", code)), default=0)
    if longest_tick >= longest_tilde:
        return "`" * max(3, longest_tick + 1)
    return "~" * max(3, longest_tilde + 1)


def _language(value: object) -> str:
    language = safe_inline_text(value)
    if re.fullmatch(r"[A-Za-z0-9_+.-]{1,32}", language or ""):
        return language
    return ""


def _render_block(block: Block) -> list[str]:
    if not block_is_visible(block):
        return []
    if isinstance(block, Paragraph):
        text = safe_paragraph_text(block.text)
        return text.split("\n") if text else []
    if isinstance(block, KeyValue):
        return [f"**{safe_inline_text(block.label)}:** {safe_inline_text(block.value)}"]
    if isinstance(block, BulletList):
        return _render_list(block)
    if isinstance(block, OrderedSteps):
        return _render_list(block, ordered=True)
    if isinstance(block, Checklist):
        return _render_list(block)
    if isinstance(block, Table):
        columns = list(block.columns)
        width = len(columns)
        if width == 0:
            return []
        rows = [list(row[:width]) + [""] * max(0, width - len(row)) for row in block.rows]
        lines = [
            "| " + " | ".join(_table_cell(value) for value in columns) + " |",
            "| " + " | ".join("---" for _ in columns) + " |",
        ]
        lines.extend("| " + " | ".join(_table_cell(value) for value in row) + " |" for row in rows)
        return lines
    if isinstance(block, CodeBlock):
        code = _normalise(block.code)
        fence = _fence(code)
        language = _language(block.language)
        return [f"{fence}{language}", *code.split("\n"), fence]
    if isinstance(block, Callout):
        text = safe_paragraph_text(block.text)
        label = safe_inline_text(block.label)
        lines: list[str] = []
        if label:
            lines.append(f"> **{label}:**")
        lines.extend("> " + line if line else ">" for line in text.split("\n"))
        return lines
    if isinstance(block, Finding):
        title = safe_heading_text(block.title, fallback="Finding")
        lines = [f"### {title}", ""]
        for label, value in (
            ("Severity", block.severity),
            ("Location", block.location),
            ("Impact", block.impact),
            ("Evidence", block.evidence),
            ("Recommendation", block.recommendation),
            ("Coverage", block.coverage),
            ("Residual risk", block.residual_risk),
            ("Conclusion", block.conclusion),
        ):
            if _nonempty(value):
                # Multiline finding fields are paragraphs after the label, not
                # arbitrary Markdown supplied by the report.
                lines.append(f"**{label}:** {safe_inline_text(value)}")
        if isinstance(block.details, Mapping):
            for label, value in block.details.items():
                if _nonempty(value):
                    rendered = _display_value(value) if isinstance(value, (Mapping, Sequence)) and not isinstance(value, (str, bytes, bytearray)) else safe_inline_text(value)
                    lines.append(f"**{safe_inline_text(label)}:** {rendered}")
        return lines
    return []


def render_markdown(document: Document) -> str:
    """Render a document with one H1, controlled lower headings, and spacing."""
    lines: list[str] = [f"# {safe_heading_text(document.title, fallback='Report')}", ""]
    if _nonempty(document.status):
        lines.append(f"**Status:** {safe_inline_text(document.status)}")
    for item in document.metadata:
        if block_is_visible(item):
            lines.append(f"**{safe_inline_text(item.label)}:** {safe_inline_text(item.value)}")
    if _nonempty(document.status) or any(block_is_visible(item) for item in document.metadata):
        lines.append("")
    if _nonempty(document.summary):
        lines.extend(safe_paragraph_text(document.summary).split("\n"))
        lines.append("")

    for section in document.sections:
        if section.is_empty():
            continue
        lines.extend((f"## {safe_heading_text(section.title)}", ""))
        first_block = True
        for block in section.blocks:
            rendered = _render_block(block)
            if not rendered:
                continue
            if not first_block and lines and lines[-1] != "":
                lines.append("")
            lines.extend(rendered)
            lines.append("")
            first_block = False

    # Trim all trailing blank lines and add exactly one final newline.  The
    # blank lines above remain deterministic separators around each block.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


class MarkdownDocumentBuilder:
    """Small fluent helper for presenters that prefer incremental assembly."""

    def __init__(self, title: object = "Report") -> None:
        self._title = title
        self._status: object | None = None
        self._summary: object | None = None
        self._metadata: list[KeyValue] = []
        self._sections: list[Section] = []

    def status(self, value: object) -> "MarkdownDocumentBuilder":
        self._status = value
        return self

    def summary(self, value: object) -> "MarkdownDocumentBuilder":
        self._summary = value
        return self

    def metadata(self, label: object, value: object) -> "MarkdownDocumentBuilder":
        self._metadata.append(KeyValue(label, value))
        return self

    def section(self, title: object, *blocks: Block) -> "MarkdownDocumentBuilder":
        self._sections.append(Section(title, blocks))
        return self

    def add_section(self, section: Section) -> "MarkdownDocumentBuilder":
        self._sections.append(section)
        return self

    def build(self) -> Document:
        return Document(
            self._title,
            status=self._status,
            summary=self._summary,
            sections=self._sections,
            metadata=self._metadata,
        )


def legacy_lines(value: object) -> list[str]:
    """Return safe, heading-free lines for old arbitrary report content."""
    if isinstance(value, Mapping):
        lines: list[str] = []
        for key, item in value.items():
            if not _nonempty(item):
                continue
            label = safe_inline_text(key)
            if isinstance(item, Mapping):
                lines.append(f"- **{label}:** {_display_value(item)}")
            elif _is_sequence(item):
                lines.append(f"- **{label}:**")
                lines.extend("    - " + _display_value(child) for child in item if _nonempty(child))
            else:
                lines.append(f"- **{label}:** {safe_inline_text(item)}")
        return lines
    if _is_sequence(value):
        return [f"- {_display_value(item)}" for item in value if _nonempty(item)]
    text = safe_paragraph_text(value)
    return text.split("\n") if text else []


__all__ = [
    "Block",
    "BulletList",
    "Callout",
    "Checklist",
    "CodeBlock",
    "Document",
    "Finding",
    "KeyValue",
    "MarkdownDocument",
    "MarkdownDocumentBuilder",
    "OrderedSteps",
    "Paragraph",
    "Section",
    "Table",
    "legacy_lines",
    "plain_text",
    "render_markdown",
    "safe_heading_text",
    "safe_inline_text",
    "safe_paragraph_text",
]
